In [7]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn import svm
from sklearn.metrics import accuracy_score

In [9]:
dataset = pd.read_csv(r'C:\Users\Dell\Downloads\diabetes.csv')

In [10]:
dataset.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  DiabetesPedigreeFunction  Age  Outcome
0            6      148             72             35        0  33.6                     0.627   50        1
1            1       85             66             29        0  26.6                     0.351   31        0
2            8      183             64              0        0  23.3                     0.672   32        1
3            1       89             66             23       94  28.1                     0.167   21        0
4            0      137             40             35      168  43.1                     2.288   33        1

In [12]:
dataset.shape

(768, 9)

In [14]:
dataset['Outcome'].value_counts()

Outcome
0    500
1    268
Name: count, dtype: int64

In [19]:
dataset.groupby('Outcome').mean()

Pregnancies     Glucose  BloodPressure  ...        BMI  DiabetesPedigreeFunction        Age
Outcome                                          ...                                                
0           3.298000  109.980000      68.184000  ...  30.304200                  0.429734  31.190000
1           4.865672  141.257463      70.824627  ...  35.142537                  0.550500  37.067164

[2 rows x 8 columns]

In [34]:
# Separating data and labels
X = dataset.drop(columns = ['Outcome'], axis=1)
Y = dataset['Outcome']

In [39]:
# Data Standardisation to make all the data bound to the same range so that our model perform better

scalar = StandardScaler()

In [40]:
scalar.fit(X)

StandardScaler()

In [43]:
X_tr = scalar.transform(X)

In [48]:
# Train Test Split

x_train,x_test,y_train,y_test = train_test_split(X_tr,Y, test_size=0.2, stratify=Y, random_state=2)

In [49]:
# Training the model

In [51]:
classifier = svm.SVC(kernel='linear')

In [52]:
classifier.fit(x_train, y_train)

SVC(kernel='linear')

In [53]:
# Model Evaluation

In [55]:
x_train_prediction = classifier.predict(x_train)
x_train_accuracy = accuracy_score(x_train_prediction, y_train)

In [56]:
x_train_accuracy

0.7866449511400652

In [61]:
x_test_prediction = classifier.predict(x_test)
x_test_accuracy = accuracy_score(x_test_prediction,y_test)

In [62]:
x_test_accuracy

0.7727272727272727

In [64]:
# Making a Prection

In [67]:
res1 =classifier.predict([[6,148,72,35,0,33.6,0.627,50]])

In [68]:
res1

array([1])

In [77]:
input2 = (1,85,66,29,0,26.6,0.351,31)
input2 = np.asarray(input2)
input2

array([ 1.   , 85.   , 66.   , 29.   ,  0.   , 26.6  ,  0.351, 31.   ])

In [79]:
input2 =input2.reshape(1,-1)
input2

array([[ 1.   , 85.   , 66.   , 29.   ,  0.   , 26.6  ,  0.351, 31.   ]])

In [81]:
input2_tr = scalar.fit_transform(input2)

In [86]:
prediction = classifier.predict(input2_tr)
prediction

array([0])